# Generated by Django 4.2 on 2023-04-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_remove_history_date_remove_history_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise_Info',
        ),
        migrations.RemoveField(
            model_name='history',
            name='log',
        ),
        migrations.RemoveField(
            model_name='workout_log',
            name='exercise',
        ),
        migrations.AddField(
            model_name='history',
            name='workout_logs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workout_app.workout_log'),
        ),
        migrations.AddField(
            model_name='workout_log',
            name='exercises',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='workout_app.exercise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workout_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_app.history'),
        ),
    ]
