# Generated by Django 4.2 on 2023-04-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0005_alter_workout_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_log',
            name='exercises',
        ),
        migrations.AddField(
            model_name='workout_log',
            name='exercises',
            field=models.ManyToManyField(null=True, related_name='workout_logs', to='workout_app.exercise'),
        ),
    ]
