# Generated by Django 4.2 on 2023-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0006_remove_workout_log_exercises_workout_log_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='workout_logs',
        ),
        migrations.AddField(
            model_name='history',
            name='workout_logs',
            field=models.ManyToManyField(null=True, related_name='history', to='workout_app.workout_log'),
        ),
    ]
